### PR TITLE
Enable ColorControl and Point

### PR DESCRIPTION
**Pull request by tmtfx**
Still in BPoint I had to comment out:

//m.attr("B_ORIGIN") = B_ORIGIN;
//m.def("operator=", &operator=, "", py::arg("other"));

B_ORIGIN I think is an important costant, but If left uncommented I could not compile. Please, take a look

### CODE REVIEW

**Comment by Zardshard** [comment]
Can't take a look at the moment, but if you post the error message the compiler gives, I might be able to figure it out quickly.

**Comment by Zardshard** [comment]
Got a chance to look. Uncommenting `//m.attr("B_ORIGIN") = B_ORIGIN;` should work. At least, it didn't give any error when I did it. As for `//m.def("operator=", &operator=, "", py::arg("other"));`, you already have it elsewhere in the code so you can safely delete that line.

**Comment by tmtfx** [comment]
Sorry, I forgot to mention that the error occurs at runtime (using python, loading Haiku-PyAPI modules) not at compile time. If I remember right, if you remove the comment, even if you don't load BPoint module in python, the app crashes saying B_ORIGIN is not defined. When I come back from work, I'll confirm this situation.
AttributeError: B_ORIGIN
...
...
ImportError: initialization failed

**Comment by tmtfx** [comment]
BTW I noticed now, in my 32bit haiku machine that ColorControl.SetValue(int) cannot be compiled
I think it works in 64bit haiku... I will confirm it as soon as I come back home

**Comment by Zardshard** [comment]
Ah, so it's a runtime error. I've encountered that kind of error before. Put the definition of B_ORIGIN after the definition of the BPoint class and Python should be happy. :slightly_smiling_face:

As for `.def("SetValue", py::overload_cast<int>(&BColorControl::SetValue), "", py::arg("color_value"))`, change the int to int32. OscarL has a relevant quote at https://github.com/coolcoder613eb/Haiku-PyAPI/pull/6

> Not sure why these functions got the wrong values for int/uint vs int32/uint32, as the Haiku header files are pretty clear about those (and directly using int32/uint32 on the .cpp files here do work).

We are getting away with using int in some places, so, it may have something to do with some of the header files that are included in some files but not others.

**Comment by Zardshard** [comment]
What's the status on this pull request? I see you pushed [Enable Point, ColorControl, RadioButton](https://github.com/coolcoder613eb/Haiku-PyAPI/commit/334f74dd92a15a2cc1c4babd2006017bcb8e968a), so I'm guessing it's ready to close?

**Comment by tmtfx** [comment]
I made a little test on my tmtest.py app for the ColorControl and RadioButton modules (although not extensive tests). They work fine,
by the way tmtest.py has some extra code for BListView and BScrollView (the latter works, the first one has some functions commented out, which I try to resolve)

**Comment by Zardshard** [comment]
I don't quite understand. Are you saying that this pull request is for your changes to tmtest.py?

**Comment by tmtfx** [comment]
I'm committing directly here You can ignore my previous pull requests

**Comment by tmtfx** [comment]
maybe I'm misunderstanding: I'm committing my modifications in this repo, before committing I run some tests written on tmtest.py

**Comment by Zardshard** [comment]
Sorry, I'm still quite confused 😵‍💫

> maybe I'm misunderstanding: I'm committing my modifications in this repo, before committing I run some tests written on tmtest.py

So what you're doing is making changes, committing them to your repository, testing them, and then pushing it to this repository?

If so, then this pull request is irrelevant as you're planning to merge the changes directly. In that case, you or I can close this PR, as we're not planning to merge it directly.

PS: Thanks for your contributions so far 🙂. You may be a beginner, but there's plenty of room for mistakes/misunderstandings/etc. in our somewhat-serious-somewhat-not project 😉

**Pull request closed without merging**
